### ISSUE TITLE
Possible misconduct and bad maners

### ISSUE THREAD

**Issue by Skylsmoi** [buxx/ggez_tests#1]
The expression "gg ez" which actually means "gg easy" is considered "bm" for Bad Manners and is a very offensive message to be given to someone else.

It is usually said at the end of an online game in place of "gg" and means "GG but it was easy, you sux noob."

I personally feel offended by the name of this repository and I will do everything that is in my power to close it.

Love, Skylsmoi.

**Comment by buxx** [comment]
:trollface:
